{% set name = "av2" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1571888e79917ee404b8898dfc4f1347abd9d07f70f6fc8245e9b00f54a48f1c

build:
  skip: true  # [py<3.8]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]

  host:
    - xorg-libxfixes  # [linux]
    - pip
    - python
    - setuptools >=42
    - wheel

  run:
    - av
    - click
    - joblib
    - matplotlib-base
    - nox
    - numba
    - numpy >=1.21.5
    - opencv
    - pandas
    - python
    - pip
    - pyarrow
    - rich
    - scipy

test:
  source_files:
    - tests
  imports:
    - av2
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/argoai/{{ name }}-api
  summary: 'The official API of the Argoverse 2 dataset.'
  description: |
    The official API of the Argoverse 2 dataset.
  license: MIT
  license_family: MIT
  license_file: 
    - LICENSE
    - NOTICE
  doc_url: https://github.com/argoai/{{ name }}-api
  dev_url: https://github.com/argoai/{{ name }}-api

extra:
  recipe-maintainers:
    - benjaminrwilson
