{% set name = "av2" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/argoai/argoverse2-api/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dcbbc7d2b7af4010fce23a6c5706c63926dc8d8148ce01e710fbd0ba66798102

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - wheel

  run:
    - av
    - click
    - joblib
    - matplotlib-base
    - nox
    - numba
    - numpy >=1.21.5
    - opencv
    - pandas
    - python >=3.8
    - pip
    - pyarrow
    - pyproj
    - rich
    - scipy

test:
  imports:
    - av2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/argoai/argoverse2-api
  summary: The official API of the Argoverse 2 dataset.
  description: |
    The official API of the Argoverse 2 dataset.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://github.com/argoai/argoverse2-api
  dev_url: https://github.com/argoai/argoverse2-api

extra:
  recipe-maintainers:
    - benjaminrwilson
